version: '3'
services:
    db:
        image: postgres:10
        environment:
            #環境変数の設定
            #直書き非推奨なので、ホストの.envから取得
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_DBNAME}
        ports:
            - "5432:5432"
        volumes:
            # db_parkinghubという名前をつけたボリュームをコンテナの/var/lib/postgresql/data にマウントするという意味
            - db_parkinghub:/var/lib/
            
    api:
        image: gilang;1.13
        working_dir: go/src/app
        volumes:
            - ./api : /go/src/app
        command:
            go run main.go
        environment:
            environment:
            #環境変数の設定
            #直書き非推奨なので、ホストの.envから取得
            - DB_HOST=db
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_USER=${DB_USER}
            - DB_DB=${DB_DBNAME}
            - LOGFILE=${LOGFILE}
        depends_on:
            - db
        ports:
            - "8080:8080"

volumes:
    #services/db/volumesで作成したdb_parkinghubというボリュームをこのコンテナで使用すると宣言
    db_parkinghub:
            
            