FROM golang:1.23

# 作業ディレクトリを設定
WORKDIR /go/src/app

# カレントディレクトリの内容をコンテナにコピー
COPY . .

# 必要なGoモジュールをインストール
RUN go mod tidy
RUN go mod download

# golang-migrateをインストール
RUN go install github.com/golang-migrate/migrate/v4/cmd/migrate@v4.15.2
# golang-migrateのCLIツールをインストール
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

# 本番用なら go build でバイナリを作成しCMDで実行
# 開発運用の場合は go run でOK
CMD ["go", "run", "main.go"]