From golang:1.13

# 作業ディレクトリを設定
WORKDIR /go/src/app

# カレントディレクトリの内容をコンテナにコピー
COPY . .

# 必要なGoモジュールをインストール
RUN go mod tidy

# golang-migrateをインストール（Go 1.13の場合は go get を推奨）
RUN go get -u github.com/golang-migrate/migrate/v4/cmd/migrate

# APIサーバのビルドなども追記
# 本番用なら go build でバイナリを作成しCMDで実行
# 開発運用の場合は go run でOK
CMD ["go", "run", "main.go"]