name: Go CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: ubuntu
          POSTGRES_DB: ubuntu
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ubuntu" --health-interval=10s --health-timeout=5s --health-retries=5

    env:
      DB_USER: ubuntu
      DB_PASSWORD: ubuntu
      DB_NAME: ubuntu
      DB_HOST: localhost
      LOGFILE: log.txt

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod tidy
        working-directory: api

      - name: Run go fmt
        run: go fmt ./...
        working-directory: api
    
      - name: Run go vet
        run: go vet ./...
        working-directory: api

      - name: Run tests
        run: go test -v ./...
        working-directory: api
